### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by BlackZon77** [rubbertoe98/DiamondBlackjack#1]
The dealer dont do animations of giving cards and other animations, and when the time of bet end's, my screen goes to the sky and not in the casino where i was

**Comment by rubbertoe98** [comment]
I cannot reproduce this, I tested the resource on a clean server build with no other resources and it works fine. Which casino interior are you using & are there any errors?

**Comment by BlackZon77** [comment]
no, there was no errors, probably its my casino interior error, i will try to change it

**Comment by BlackZon77** [comment]
i dont think that the problem is my casino because all peds stay in the right table etc, i sit right etc, well the part of the animations i think its working, but when i place a bet and the time ends, every player get their screen in the sky

https://prnt.sc/r2xxrw
https://prnt.sc/r2xy1o
https://prnt.sc/r2xy6t

**Comment by Vyve-AU** [comment]
As per a reply I made on the FiveM forums, do you use esx_kashacters?
I did some testing, and it seems that the scripted cameras in esx_kashacters somehow conflict with those provided in this script.
Once I disabled kashacters, everything worked fine.
@BlackZon77

**Comment by BlackZon77** [comment]
Oh,the thing is i need esx_kashacters ..., thanks for let me knowing,

**Comment by neoreturns** [comment]
Comment out the functions that run, problem solved:

SetCamParams
ShakeCam
RenderScriptCams

~ Crypto

**Comment by rubbertoe98** [comment]
Fixedt
