### ISSUE TITLE
BLACKAJACK BREAKING CAR SOUNDS

### ISSUE THREAD

**Issue by DTK7** [rubbertoe98/DiamondBlackjack#10]
hi your blackjack breaks casino dlc car sounds. anmy fiix  for it?

**Comment by arthur-rl** [comment]
Hi, if you’re running b2060 server you can just delete the files from the resource

**Comment by Minimalistic09** [comment]
Same problem, what files we need to delete?

**Comment by arthur-rl** [comment]
The `audio` folder.
