### ISSUE TITLE
issue with reward and chips

### ISSUE THREAD

**Issue by Termin44l** [rubbertoe98/DiamondBlackjack#13]
Hey! I got this issue that if you don't have chip balance you still can bet and if you win you don't get anything.

**Comment by arthur-rl** [comment]
The Blackjack script doesn't come with any balance checking.

to add chips/money into your framework/gamemode complete the two functions named `tryTakeChips` and `giveChips` at the top of sv_blackjack.lua

**Comment by JiminyKroket** [comment]
Example following:
```
function tryTakeChips(source,amount)
  --returns true if taken chips succesfully
  --returns false if doesn't have enough chips
  local hasEnough = false
  TriggerEvent('SSCasino:getPlayerChips', source, amount, function(didTake)
    if didTake then
      hasEnough = true
    end
  end)
  return hasEnough
end

function giveChips(source,amount)
    --gives amount in chips to source
    TriggerEvent('SSCasino:gainedFromBlackjack', source, amount)
end
```

**Comment by rubbertoe98** [comment]
That's because your TriggerEvent is async and the function is synchronous so will always returns false.
